name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou"
database_id = "a9a66401-8a44-4698-aab8-63a1f5e42f6c"

[version_metadata]
binding = "CF_VERSION_METADATA"
